apiVersion: v1
kind: ReplicationController
metadata:
 name: myrc
 labels:
  app: web1  #  this is the label of RC not label of pods

spec:
 replicas: 3  #  always one pod will be present even in case of current worker node failure
 template:
  metadata:
   name: mypod  #  this will be the podname that will be created by RC
   labels:
    x: hellolavi
  spec:
   containers:
    - name: mycon
      image: nginx
      ports:
       - containerPort: 80 