apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloenv1
  name: lavienv1
spec:
  containers:
  - image: dockerashu/ckad:v2
    name: lavienv1
    ports:
    - containerPort: 1120
    env:
      - name: color
        value: green
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
